In [ ]:
# Project 1: Explore DC_Properties.csv dataset

# Explore the data

In [3]:
#import libraries
import pandas as pd
import numpy as np
#load data with headers
location = "datasets/DC_Properties.csv"
df = pd.read_csv(location)

C:\Users\Administrator\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (18,19,20,21,22,23,24,33,34,35,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
#look at first 5 rows of data
df.head()

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW

In [5]:
#look at last 5 rows of data
df.tail()

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
158952,158952,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,...,-77.01942,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158953,158953,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.01942,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158954,158954,2,0,Forced Air,Y,NaN,4,2,1920.0,2007.0,...,-77.01942,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158955,158955,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.01823,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW
158956,158956,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.01823,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW

In [7]:
#show column names
df.columns

Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE', 'NATIONALGRID',
       'LATITUDE', 'LONGITUDE', 'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD',
       'CENSUS_TRACT', 'CENSUS_BLOCK', 'WARD', 'SQUARE', 'X', 'Y', 'QUADRANT'],
      dtype='object')

In [9]:
#show data type of each column
df.dtypes

Unnamed: 0              int64
BATHRM                  int64
HF_BATHRM               int64
HEAT                   object
AC                     object
NUM_UNITS             float64
ROOMS                   int64
BEDRM                   int64
AYB                   float64
YR_RMDL               float64
EYB                     int64
STORIES               float64
SALEDATE               object
PRICE                 float64
QUALIFIED              object
SALE_NUM                int64
GBA                   float64
BLDG_NUM                int64
STYLE                  object
STRUCT                 object
GRADE                  object
CNDTN                  object
EXTWALL                object
ROOF                   object
INTWALL                object
KITCHENS              float64
FIREPLACES              int64
USECODE                 int64
LANDAREA                int64
GIS_LAST_MOD_DTTM      object
SOURCE                 object
CMPLX_NUM             float64
LIVING_GBA            float64
FULLADDRESS            object
CITY                   object
STATE                  object
ZIPCODE               float64
NATIONALGRID           object
LATITUDE              float64
LONGITUDE             float64
ASSESSMENT_NBHD        object
ASSESSMENT_SUBNBHD     object
CENSUS_TRACT          float64
CENSUS_BLOCK           object
WARD                   object
SQUARE                 object
X                     float64
Y                     float64
QUADRANT               object
dtype: object

In [10]:
#count rows
len(df)

158957

In [11]:
#number of non-NA values
df.count()

Unnamed: 0            158957
BATHRM                158957
HF_BATHRM             158957
HEAT                  158957
AC                    158957
NUM_UNITS             106696
ROOMS                 158957
BEDRM                 158957
AYB                   158686
YR_RMDL                80928
EYB                   158957
STORIES               106652
SALEDATE              132187
PRICE                  98216
QUALIFIED             158957
SALE_NUM              158957
GBA                   106696
BLDG_NUM              158957
STYLE                 106696
STRUCT                106696
GRADE                 106696
CNDTN                 106696
EXTWALL               106696
ROOF                  106696
INTWALL               106696
KITCHENS              106695
FIREPLACES            158957
USECODE               158957
LANDAREA              158957
GIS_LAST_MOD_DTTM     158957
SOURCE                158957
CMPLX_NUM              52261
LIVING_GBA             52261
FULLADDRESS           106040
CITY                  106051
STATE                 106051
ZIPCODE               158956
NATIONALGRID          106051
LATITUDE              158956
LONGITUDE             158956
ASSESSMENT_NBHD       158956
ASSESSMENT_SUBNBHD    126406
CENSUS_TRACT          158956
CENSUS_BLOCK          106051
WARD                  158956
SQUARE                158957
X                     158720
Y                     158720
QUADRANT              158720
dtype: int64

In [12]:
#look at the data in the PRICE column
df['PRICE'].max()

137427545.0

In [13]:
df['PRICE'].min()

1.0

In [14]:
df['PRICE'].mean()

931351.5949336156

In [15]:
df['PRICE'].median()

399999.0

In [16]:
df['PRICE'].mode()

0    350000.0
dtype: float64

In [17]:
df['PRICE'].value_counts()

350000.0     595
250000.0     536
300000.0     523
450000.0     519
375000.0     488
325000.0     482
550000.0     459
275000.0     455
500000.0     426
320000.0     425
200000.0     422
425000.0     419
600000.0     403
315000.0     402
330000.0     396
650000.0     387
525000.0     387
285000.0     377
225000.0     376
265000.0     374
310000.0     371
475000.0     364
360000.0     364
260000.0     360
280000.0     352
385000.0     352
335000.0     352
220000.0     349
240000.0     348
230000.0     347
            ...
168700.0       1
674755.0       1
5397500.0      1
168670.0       1
674670.0       1
468400.0       1
337325.0       1
1096000.0      1
337562.0       1
1350250.0      1
337575.0       1
117164.0       1
84461.0        1
468890.0       1
84450.0        1
84449.0        1
503850.0       1
337750.0       1
675490.0       1
114620.0       1
466250.0       1
468776.0       1
337700.0       1
234384.0       1
937499.0       1
337650.0       1
675265.0       1
468674.0       1
21100.0        1
648150.0       1
Name: PRICE, Length: 13486, dtype: int64

In [22]:
df['PRICE'].describe()

count    9.821600e+04
mean     9.313516e+05
std      7.061325e+06
min      1.000000e+00
25%      2.400000e+05
50%      3.999990e+05
75%      6.520000e+05
max      1.374275e+08
Name: PRICE, dtype: float64

In [25]:
#Cleaning up the data
#check for duplicated rows
dupe=df.duplicated()
df.loc[dupe]

Empty DataFrame
Columns: [Unnamed: 0, BATHRM, HF_BATHRM, HEAT, AC, NUM_UNITS, ROOMS, BEDRM, AYB, YR_RMDL, EYB, STORIES, SALEDATE, PRICE, QUALIFIED, SALE_NUM, GBA, BLDG_NUM, STYLE, STRUCT, GRADE, CNDTN, EXTWALL, ROOF, INTWALL, KITCHENS, FIREPLACES, USECODE, LANDAREA, GIS_LAST_MOD_DTTM, SOURCE, CMPLX_NUM, LIVING_GBA, FULLADDRESS, CITY, STATE, ZIPCODE, NATIONALGRID, LATITUDE, LONGITUDE, ASSESSMENT_NBHD, ASSESSMENT_SUBNBHD, CENSUS_TRACT, CENSUS_BLOCK, WARD, SQUARE, X, Y, QUADRANT]
Index: []

[0 rows x 49 columns]

In [26]:
#PRICE has 98216 non-NA values. Since there are 158957 rows, there are many rows without a price. 
#Create a new dataframe eliminating those null rows
df = df.dropna(axis=0, subset=['PRICE'])

In [27]:
len (df)

98216

In [29]:
#OMG - it worked!!!!
df['PRICE'].describe()

count    9.821600e+04
mean     9.313516e+05
std      7.061325e+06
min      1.000000e+00
25%      2.400000e+05
50%      3.999990e+05
75%      6.520000e+05
max      1.374275e+08
Name: PRICE, dtype: float64

In [35]:
#further reduce table to rows where price is between 25% and 75% percentil of values -- ie,, the middle 50% of prices
midprices = df.loc[(df['PRICE'] > 240000) & (df['PRICE'] < 652000)]
midprices

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
19,19,3,1,Hot Water Rad,Y,2.0,9,3,1908.0,2013.0,...,-77.040138,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
37,37,2,2,Warm Cool,Y,2.0,8,4,1800.0,2009.0,...,-77.033367,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
45,45,3,1,Forced Air,Y,2.0,10,5,1890.0,2009.0,...,-77.032744,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
48,48,2,1,Forced Air,N,2.0,8,3,1976.0,NaN,...,-77.032951,Old City 2,040 E Old City 2,5201.0,005201 4002,Ward 2,208,-77.033366,38.911716,NW
54,54,1,1,Forced Air,Y,2.0,4,2,1900.0,2004.0,...,-77.033705,Old City 2,040 E Old City 2,5201.0,005201 4002,Ward 2,208,-77.033366,38.911716,NW
58,58,1,0,Hot Water Rad,N,2.0,4,1,1885.0,2004.0,...,-77.035053,Old City 2,040 E Old City 2,4300.0,004300 2006,Ward 2,191,-77.035454,38.914956,NW
61,61,3,1,Forced Air,Y,2.0,8,3,1890.0,2002.0,...,-77.034845,Old City 2,040 E Old City 2,4300.0,004300 2006,Ward 2,191,-77.035454,38.914956,NW
65,65,3,1,Hot Water Rad,Y,3.0,8,3,1885.0,2007.0,...,-77.035811,Old City 2,040 E Old City 2,4300.0,004300 2003,Ward 2,191,-77.035454,38.914956,NW
69,69,3,1,Hot Water Rad,N,3.0,10,4,1885.0,2009.0,...,-77.034889,Old City 2,040 E Old City 2,5201.0,005201 2000,Ward 2,192,-77.034848,38.913055,NW
77,77,2,1,Warm Cool,Y,2.0,11,3,1979.0,NaN,...,-77.037762,Old City 2,040 D Old City 2,4201.0,004201 1002,Ward 2,176,-77.037830,38.916190,NW
92,92,2,0,Hot Water Rad,N,1.0,7,4,1909.0,NaN,...,-77.048449,Foggy Bottom,NaN,10800.0,010800 3004,Ward 2,81,-77.047880,38.897076,NW
132,132,1,0,Warm Cool,Y,1.0,6,3,1908.0,2006.0,...,-77.040373,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
157,157,2,0,Warm Cool,Y,1.0,6,3,1904.0,2004.0,...,-77.038867,Old City 2,040 D Old City 2,4201.0,004201 2000,Ward 1,149,-77.038764,38.918277,NW
161,161,1,1,Warm Cool,Y,1.0,6,3,1880.0,2013.0,...,-77.039217,Old City 2,040 D Old City 2,4201.0,004201 2002,Ward 1,150,-77.039567,38.917462,NW
165,165,3,1,Forced Air,Y,2.0,7,2,1890.0,2005.0,...,-77.033842,Old City 2,040 E Old City 2,5201.0,005201 4002,Ward 2,208,-77.033366,38.911716,NW
169,169,3,0,Forced Air,Y,3.0,10,4,1911.0,2004.0,...,-77.034190,Old City 2,040 E Old City 2,5201.0,005201 4002,Ward 2,208,-77.033366,38.911716,NW
185,185,1,1,Warm Cool,Y,1.0,8,3,1888.0,NaN,...,-77.033383,Old City 2,040 E Old City 2,5201.0,005201 4004,Ward 2,209,-77.033446,38.910498,NW
190,190,2,0,Warm Cool,Y,2.0,6,3,1880.0,NaN,...,-77.032993,Old City 2,040 E Old City 2,5201.0,005201 4004,Ward 2,209,-77.033446,38.910498,NW
197,197,2,0,Hot Water Rad,N,1.0,8,5,1880.0,2004.0,...,-77.033599,Old City 2,040 E Old City 2,5201.0,005201 4004,Ward 2,209,-77.033446,38.910498,NW
201,201,2,0,Warm Cool,Y,2.0,9,3,1905.0,NaN,...,-77.037434,Old City 2,040 D Old City 2,4201.0,004201 1004,Ward 2,177,-77.037221,38.915033,NW
205,205,3,0,Warm Cool,Y,2.0,9,3,1890.0,2009.0,...,-77.037577,Old City 2,040 D Old City 2,4201.0,004201 1006,Ward 2,177,-77.037221,38.915033,NW
219,219,1,0,Warm Cool,Y,1.0,6,3,1890.0,1950.0,...,-77.037448,Old City 2,040 D Old City 2,4201.0,004201 1006,Ward 2,177,-77.037221,38.915033,NW
222,222,1,0,Warm Cool,Y,2.0,6,3,1890.0,NaN,...,-77.037268,Old City 2,040 D Old City 2,4201.0,004201 1006,Ward 2,177,-77.037221,38.915033,NW
231,231,1,1,Warm Cool,Y,1.0,7,2,1900.0,1980.0,...,-77.037189,Old City 2,040 D Old City 2,4201.0,004201 1003,Ward 2,177,-77.037221,38.915033,NW
237,237,1,1,Warm Cool,Y,1.0,5,2,1880.0,1985.0,...,-77.037263,Old City 2,040 D Old City 2,4201.0,004201 1003,Ward 2,177,-77.037221,38.915033,NW
253,253,3,1,Hot Water Rad,N,2.0,13,7,1890.0,2011.0,...,-77.046372,Old City 2,040 D Old City 2,5500.0,005500 1004,Ward 2,93,-77.045889,38.912003,NW
255,255,3,1,Warm Cool,Y,2.0,8,4,1978.0,NaN,...,-77.045512,Old City 2,040 D Old City 2,5500.0,005500 1004,Ward 2,93,-77.045889,38.912003,NW
256,256,3,1,Warm Cool,Y,2.0,8,3,1978.0,NaN,...,-77.045590,Old City 2,040 D Old City 2,5500.0,005500 1004,Ward 2,93,-77.045889,38.912003,NW
261,261,1,0,Forced Air,Y,1.0,6,2,1900.0,1998.0,...,-77.052347,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
263,263,2,1,Forced Air,Y,1.0,5,3,1910.0,2004.0,...,-77.052887,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158907,158907,1,0,Forced Air,Y,NaN,4,1,1918.0,2005.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158908,158908,1,0,Forced Air,Y,NaN,4,1,1918.0,2005.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158910,158910,2,0,Forced Air,Y,NaN,4,1,1932.0,2006.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158911,158911,2,0,Forced Air,Y,NaN,4,2,1932.0,2006.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158914,158914,2,1,Forced Air,Y,NaN,4,2,2014.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158915,158915,1,0,Forced Air,Y,NaN,3,1,2014.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158916,158916,1,0,Forced Air,Y,NaN,3,1,2014.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158924,158924,1,0,Ht Pump,Y,NaN,5,2,1993.0,1993.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158926,158926,1,0,Ht Pump,Y,NaN,5,2,1993.0,1993.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158928,158928,2,1,Ht Pump,Y,NaN,5,2,2013.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158929,158929,2,1,Ht Pump,Y,NaN,5,2,2013.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158930,158930,2,0,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158931,158931,2,1,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158932,158932,2,1,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158933,158933,2,0,Ht Pump,Y,NaN,4,2,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158934,158934,1,1,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158935,158935,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158936,158936,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158939,158939,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158943,158943,2,1,Forced Air,Y,NaN,5,2,2004.0,2004.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158945,158945,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158946,158946,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158947,158947,2,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158948,158948,2,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158949,158949,1,1,Forced Air,Y,NaN,4,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158950,158950,3,0,Forced Air,Y,NaN,5,3,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158951,158951,3,1,Forced Air,Y,NaN,5,3,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158952,158952,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158953,158953,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158954,158954,2,0,Forced Air,Y,NaN,4,2,1920.0,2007.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW

In [37]:
#Check to see the difference in the maximum number of bathrooms for the whole data set vs. for the dataset containing the middle
# 50% of prices
midprices['BATHRM'].max()

9

In [38]:
df['BATHRM'].max()

12

In [39]:
#Check to see the difference in the number of bedrooms for the whole data set vs. for the dataset containing the middle 50%
midprices['BEDRM'].max()

13

In [40]:
df['BEDRM'].max()

20

In [47]:
df['PRICE'].groupby(df['QUADRANT']).mean()

QUADRANT
NE    3.928715e+05
NW    1.317785e+06
SE    3.682260e+05
SW    3.470489e+05
Name: PRICE, dtype: float64

In [ ]:
#Interesting things to conclude about the data:
# Some fields have null values. For a column like 'PRICES', more than 1/3 of the rows have null values (about 60K out of 150K).
# I learned how to eliminate those rows. I also learned how to create a slice of the data containing only certain values. By
# slicing out the houses whose prices fall in the middle 50%, I could see that those middle 50% run from $250K to $650K. That
# makes the housing prices in DC seem not as outrageously high as I had assumed. The mean of the data is $399,999 but the median is
# $931,351. So it appears that there must be a lot of really expensive houses that inflate the mean. When you slice the data by 
# quadrant, you can see that those expensive houses that skew the mean are in the NW because the mean for the NW is about 4 times
# that of the other 3 quadrants.